#!/usr/bin/env sh

hc() {
    herbstclient "$@"
}

hc emit_hook reload

sxhkd &
picom -b &
setxkbmap pl
flameshot &
flashfocus &
dunst &

# sh ~/Scripts/runxmobar.sh &
sh ~/.screenlayout/herbstluftwm.sh &

# solid background
# hsetroot -solid '#3e2929'
~/.fehbg

# remove all existings keybindings
hc keyunbind --all 
hc mouseunbind --all

Mod=Mod1

hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize


# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# frame settings
hc set frame_border_active_color '#473428'
hc set frame_border_normal_color '#3c2b22'
hc set frame_bg_normal_color '#443a36'
hc set frame_bg_active_color '#79695a'
hc set frame_border_width 0
hc set always_show_frame false
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 35
hc set snap_gap 18

# Window settings
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

hc attr theme.active.color '#201e1a'
hc attr theme.normal.color '#201e1a'
# hc attr theme.normal.color '#443a36'
# hc attr theme.active.color '#79695a'
hc attr theme.border_width 9
hc attr theme.inner_width 2
hc attr theme.floating.inner_width 2
hc attr theme.padding_top 0
hc attr theme.padding_bottom 0 # 19
hc attr theme.floating.padding_left 0 #21
hc attr theme.floating.padding_bottom 0
hc attr theme.floating.border_width 9
hc attr theme.active.inner_color '#473428'
hc attr theme.normal.inner_color '#3c2b22'
hc attr theme.floating.active.inner_color '#473428'
hc attr theme.floating.normal.inner_color '#3c2b22'
hc attr theme.background_color '#201e1a'

# tags
tag_names=("Chat" "Music" "Editor" "Web" "Extra")
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do  
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc set tree_style '╾│ ├└╼─┐'

# rules

hc unrule -F
# hc rule focus=on # normally focus new clients
hc rule focus=on # normally do not focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=on

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
